# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'

    - name: Test
      run: go test -v ./...

    - name: Build Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -v -o dmrfill-linux-amd64

    - name: Build Linux arm64
      run: GOOS=linux GOARCH=arm64 go build -v -o dmrfill-linux-arm64

    - name: Build MacOS amd64
      run: GOOS=darwin GOARCH=amd64 go build -v -o dmrfill-darwin-amd64

    - name: Build MacOS arm64
      run: GOOS=darwin GOARCH=arm64 go build -v -o dmrfill-darwin-arm64
